#
# COPYRIGHT Ericsson 2024
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "eric-oss-endc-flm-poc.fullname" . }}-database-pg-secret
  labels:
  {{- include "eric-oss-endc-flm-poc.labels" . | nindent 4 }}
  annotations:
  {{- include "eric-oss-endc-flm-poc.annotations" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := (index .Values "eric-oss-endc-flm-poc-database-pg" "secrets") }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
