#
# COPYRIGHT Ericsson 2024
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

#Metrics related configurations
management.endpoints.web.exposure.include: "*"
management.endpoint.info.enabled: "true"
management.endpoint.metrics.enabled: "true"
management.endpoint.prometheus.enabled: "true"
management.prometheus.metrics.export.enabled: "true"
management.metrics.web.server.auto-time-requests: "true"
management.info.env.enabled: "true"

#opentracing.jaeger.enabled: "true"

spring:
  profiles:
    active: "production"
  jackson:
    default-property-inclusion: "non_null"
  datasource:
    url: ${DB_URL:jdbc:postgresql://eric-oss-endc-flm-poc-database-pg:5432/eric-oss-endc-flm-poc}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  kafka:
    schema-registry:
      url: ${SCHEMA_REGISTRY:http://eric-schema-registry-sr:8081}
  security.oauth2.client:
    registration.eic:
      authorization-grant-type: client_credentials
      client-id: ${CLIENT_ID:}
      client-secret: ${CLIENT_SECRET:}
    provider.eic.token-uri: ${IAM_URL:}/auth/realms/${TENANT:master}/protocol/openid-connect/token

endpoints:
  health:
    sensitive: "false"

info:
  app:
    name: '@name@'
    description: Microservice chassis app
    version: '@version@'
    legal: "COPYRIGHT Ericsson 2024 -
 The copyright to the computer program(s) herein is the property of
 Ericsson Inc. The programs may be used and/or copied only with written
 permission from Ericsson Inc. or in accordance with the terms and
 conditions stipulated in the agreement/contract under which the
 program(s) have been supplied."

#See more details about pattern layout: https://logging.apache.org/log4j/1.2/apidocs/org/apache/log4j/PatternLayout.html
#See more details about logging.pattern.level : https://docs.spring.io/spring-boot/docs/2.5.2/reference/html/features.html#features.logging.custom-log-configuration
#logging.pattern.level: "%5p [%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-}][%X{userName}]"

#Set the stubrunner credentials:
#stubrunner.username: <LAN SIGNUM ID>
#stubrunner.password: <LAN encripted PWD or JFrog API Key>
stubrunner:
  username: ${SELI_ARTIFACTORY_REPO_USER}
  password: ${SELI_ARTIFACTORY_REPO_PASS}

rapp-sdk:
  dcc:
    enabled: ${DCC_ENABLED:true}
    base-path: ${BASE_URL:http://localhost}/dmm-data-collection-controller
  cellCapacityCalcType:
    usingCellWeight: true
  catalog:
    base-path: ${BASE_URL:}/dmm-data-catalog
  bdr:
    enabled: "true"
    service: ${BDR_SERVICE:http://eric-data-object-storage-mn:9000}
    bucket: "endcflm"
    access-key: ${BDR_ACCESSKEY:minioadmin}
    secret-key: ${BDR_SECRETKEY:minioadmin}
  ncmp:
    enabled: true
    base-path: ${BASE_URL:http://localhost}/ncmp
  kafka:
    group-prefix: endc-flm-rapp
    bootstrapServers: ${KAFKA_SERVICE:eric-oss-dmm-kf-op-sz-kafka-bootstrap:9092}
    enabled: true
    autoStart: true
    consumers:
      nrPmCounters:
        group-id: nrpmcounters
        topics: eric-oss-3gpp-pm-xml-ran-parser-nr
        listener-class: nrPmCounterDataRetrieval
      ltePmCounters:
        group-id: ltepmcounters
        topics: eric-oss-3gpp-pm-xml-ran-parser-lte
        listener-class: ltePmCounterDataRetrieval

app:
  data:
    customerid: ${CUSTOMER_ID:netsim}
    pm:
      rop:
        millis: 900000
        scheduler:
          cron: "0 14,29,44,59 * * * *"
  security:
    certificates: ${CA_CERT_PATH:}

cm-extract:
  batchSize: 20